{% set name = "diffprivlib" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2a154d83272e06bc5ba08b1c733e1fe544de74b35e5ee32c495a5bee7cd439f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - joblib >=0.13.2
    - numpy >=1.15.0
    - python
    - scikit-learn >=0.20.3
    - scipy >=1.2.1

test:
  imports:
    - diffprivlib
    - diffprivlib.mechanisms
    - diffprivlib.mechanisms.transforms
    - diffprivlib.models
    - diffprivlib.tools

about:
  home: https://github.com/IBM/differential-privacy-library
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: IBM Differential Privacy Library
  doc_url: https://pypi.org/project/diffprivlib/
  dev_url: https://github.com/IBM/differential-privacy-library

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
